### ISSUE TITLE
Updating quo-connect.php

### ISSUE THREAD

**Issue by theritesite** [zao-web/quickbooks-online-connect-ui#2]
When experimenting with this plugin, the composer install created an out of date version of the /vendor/zao-web/qbo-connect/qbo-connect.php

The composer creates version 0.1.0 and the piece it is created from --
https://github.com/zao-web/quickbooks-online-connect/blob/master/qbo-connect.php 
-- is on version 0.1.3

The old version is missing the "token_acquired()" function in the Connect class, which throws an error when trying to activate the plugin.

This plugin is a life saver, thanks for doing some hard work and letting it be open source!

**Comment by jtsternberg** [comment]
Yah, I've found that there are sometimes bugs like this when using [`"dev-master"`](https://github.com/zao-web/quickbooks-online-connect-ui/blob/788f986a452679ce10b06605e757a00bb2633fbc/composer.lock#L116) with composer. I think it should be good now as I've updated to defining by the version.

We're glad you like it!
