### ISSUE TITLE
Update CMB2 library

### ISSUE THREAD

**Issue by RPillz** [zao-web/quickbooks-online-connect-ui#3]
I just installed your WooCommerce Quickbooks plugin. (Thank you!) and it created a fatal error due to an older CMB2 library not being compatible with PHP 7.2.

The composer file in this project should be updated to use https://github.com/CMB2/CMB2, as the current package has been abandoned.

**Comment by JustinSainton** [comment]
Glad to see you're getting some usage out of the plugin! We'll update that dependency straight away. Cheers!
